# Header
menu:
  Arvhives: /archives
  Categories: /categories
  Tags: /tags
  Projects: /projects
  Knowledge: http://lib.jeoygin.org
  About: /about

# SubNav
subnav:
  github: "https://github.com/jeoygin"
  # weibo: "#"
  # facebook: "#"
  # google: "#"
  # twitter: "#"
  linkedin: "https://www.linkedin.com/pub/ruijian-wang/36/19/561"
  rss: "/atom.xml"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true

# Miscellaneous

favicon: /favicon.ico

#你的头像
avatar: "https://avatars3.githubusercontent.com/u/2769575?v=3&s=460"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称
duoshuo: jeoygin
#是否开启云标签
#tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
# friends:
#  My Library: http://lib.jeoygin.org/

#是否开启“关于我”。
#不开启——
aboutme: false
#开启——
# aboutme: 我是谁，我从哪里来，我到哪里去？我就是我，是颜色不一样的吃货…

google_analytics: UA-56551350-1
baidu_tongji: true
